### ISSUE TITLE
Is it possible to run iblrig without Alyx?

### ISSUE THREAD

**Issue by nmtimme** [int-brain-lab/iblrig#355]
Hello

I'm working on setting up the IBL rig and I was wondering if it is possible to run the task without connecting to Alyx. I'm asking because (1) I'm not sure if I want to use Alyx to manage the data and (2), even if I do end up using Alyx, it would be nice to be able to work on testing the rig while I'm also setting up Alyx. I looked through previous issues and the IBL documentation for setting up the rig, but I couldn't find anything addressing this question. However, if I missed it, I apologize and I would appreciate it if you could point me in the right direction. Thanks!

~Nick

**Comment by nbonacchi** [comment]
Hi @nmtimme 
I'm currently working on a big update for the rig, where this should be fixed, i.e. the ONE/Alyx calls are atm relegated to the end and don't prevent data acquisition. You can use this code by checking out the develop branch, running `python update-py -b develop` should install the rig on that branch.
iblrig's release procedure involves a pre-reslease step where we test the rig output from the release candidate branch (rc) on a couple of production rigs (with different hw configurations) before merging to master. The reason I'm mentioning this is because the develop branch can become unstable. At the moment the tests pass and all the tasks run, but as it's the main branch where I merge all the different changes I'm working on so this can change at any moment. 
Having said that it would be great to have another "tester" reporting their experience, so as long as you're not expecting production level performance and you're testing things out the develop branch should be OK. 
You can see the changes from the latest release in the release_notes.md file in the repo root.

NB: A couple of things:
- calling `pybpod` will detect you are on the develop branch and ask you if you want to update to the latest release, just answer no when prompted.
- I hope to merge into the rc branch (pre-release) within this/next week so a new task version should come soon(ish).
- The best place to find info on the rig sw is [here](https://figshare.com/articles/preprint/A_standardized_and_reproducible_method_to_measure_decision-making_in_mice_Appendix_3_IBL_protocol_for_setting_up_the_behavioral_training_rig/11634732), though I think you have this link already. The rig is composed by a panoply of different technologies and each one of them have their own docs I believe the links for most of the hw/sw we use are also in the document I shared. In any case a simple google search using any of the following words should also be helpful: pybpod, bonsai-rx, bpod, bonvision, PointGray

**Comment by nmtimme** [comment]
Thanks for that information! I was able to switch over to the development branch and start pybpod. 

Following the instructions for setting up the rig, the next step was to calibrate the frame2TTL. I ran this protocol and it wasn't able to recommend a threshold. This is an improvement over my previous attempts where nothing was output, so it seems moving to the development branch helped with that. The rig setup manual says to check the IR filter on the frame2TTL sensor, which I will do. However, should I see anything on the screen during this calibration? I don't see any change in the screen near the sensor. I recognize this question is probably outside the scope of my original question, so feel free to push this to a different issue. I looked through the old issues and couldn't find anything on this point, but if I missed it, I'm sorry. Please direct me to a good resource to answer this question.

Thanks!

~Nick

**Comment by nbonacchi** [comment]
Hi @nmtimme,
Great catch...
I'm refactoring all the logic of who calls what during task initiation and termination procedures and I forgot to update the calibration tasks...   It will still change but it should work for now :)

**Comment by nbonacchi** [comment]
oh right... to update just  `python update.py -b develop` again.

**Comment by nmtimme** [comment]
Hi @nbonacchi ,

That doesn't seem to have resolved the error. I tried reinstalling iblrig from the beginning, but I still get the same error on the develop branch.

~Nick

**Comment by nbonacchi** [comment]
The update.py actually reinstalls all the dependencies from scratch
There is a weird asynchronous thing with it where the Bonsai installation takes a while to start but the script tells you it's over...
Make sure you have the latest commit on developthe error has to be gone or at least different :open_mouth:

**Comment by nmtimme** [comment]
Hi @nbonacchi ,

I just tried updating develop again and I noticed this error, which seems to be related to Bonsai. See below:

![image](https://user-images.githubusercontent.com/38138179/118857592-38164e80-b8a6-11eb-8440-916af9438b19.png)

I also noticed when I reinstalled iblrig that it asked to install Bonsai. Should I have not installed it earlier in the setup process from the Bonsai website (version 2.6.2) per instructions?

Thanks!

~Nick

**Comment by nbonacchi** [comment]
Installing Bonsai manually from the executable package is a way of making sure that the Windows dependencies are present. I have to verify if this new deployment strategy develop is using deprecates this step or not, in any case as far as the rig code is concerned it really does not matter as it calls its own specially configured Bonsai.exe app. Because Bonsai is a portable application it can happily cohabitate with other Bonsais that have different configurations. It gets confusing though as double-clicking on a workflow will open the system Bonsai which may be configured differently. In the instructions there is an optional step to remove the System Bonsai just because of this.

Regarding your error, it looks like something weird with Bonsai installation and the update script that is still looking for the old executable.
you can try manually deleting the Bonsai folder inside iblrig then from a command prompt type `git reset --hard` finally `python update.py --upgrade-bonsai`

**Comment by nmtimme** [comment]
Hi @nbonacchi ,

That seems to have resolved that problem! The Bonsai window now appears on the ipad with a small purple/white patch in the lower right hand corner. When I ran it without the sensor attached to see the patch, it said that the threshold could not be found and it did not error. However, when I attached the sensor, I received this error, which appears to be related to alyx.

![image](https://user-images.githubusercontent.com/38138179/118866313-db1f9600-b8af-11eb-8580-67a7bd04d629.png)

Let me know if you have any suggestions on how to proceed. Thanks!

~Nick

**Comment by nbonacchi** [comment]
Yup that's expected. Things are saved locally in a params file and the last thing the task tries to do is to sync w Alyx the new values. In your case that will fail, but the calibration should be done. I'm working in making the error less "scary", i.e. catch it and display a useful message to the user.

**Comment by nmtimme** [comment]
Ah, I see. I checked the params file and indeed there are values for the F2TTL threshold now. Thanks!
